### ISSUE TITLE
Staging - serwer przejściowy

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/petycja-php.siecobywatelska.pl#25]
Szanowny, 

Uważam, że aplikacja osiągnęła taki poziom rozwoju, że przydało by się skonfigurować jakiś serwer, który będzie pokazywać wersje deweloperską tej aplikacji szerszej publice.  Wskazane jest zatem znalezienie serwera FTP oraz bazy danych MySQL. Prośbę te kieruje głównie do naszego administratora serwerami @ad-m. Proszę o przesłanie danych autoryzacyjnych via e-mail/SMS.  Skonfiguruje wtedy automatyczny deploy via  Codeship/Travis-CI. 

Z wyrazami szacunku

**Comment by ad-m** [comment]
Pragnę stwierdzić, że sam serwer FTP i PHP nie wydają się dostateczne do uruchamiania aplikacji na serwerze. A wersja PHP? Czy .htaccess? Niewiele informacji to zrobię byle jak.

**Comment by mik-laj** [comment]
Mamy aplikacje napisana w najnowszym CakePHP. Wymagania są na stronie projektu, ale w sumie to PHP 5.4 i jakis MySQL. htacesa też się przyda, ale moge spróbować z nginxem zrobić, jeśli takie są możliwości.

**Comment by ad-m** [comment]
Host: grazyna.jawne.info.pl
Login: travis@petycje.staging.siecobywatelska.pl
Hasło: {SMS}

**Comment by mik-laj** [comment]
Walczę dzisiaj z tym. Mam nadzieje, że do jutra uda się to skonfigurować.

**Comment by ad-m** [comment]
Czy jest możliwość zabezpieczenia tego hasłem?

**Comment by mik-laj** [comment]
Login: jablko
Hasło: rzodkiewka
@ka54mil

**Comment by mik-laj** [comment]
``` bash
git stash -u 
git checkout staging
git reset --hard master
git push 
git checkout master
git stash apply
```

**Comment by ka54mil** [comment]
Login: rzodkiewka
Hasło: jablko
