### ISSUE TITLE
Możliwość wyświetlania  listy wpisów

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/petycja-php.siecobywatelska.pl#4]
Szanowny,

Użytkownik wchodzący na stronę powinien mieć możliwość wyświetlenia listy wpisów w sposób chronologiczny biorąc pod uwagę, że niektóre wpisy mogą być przypięte, co oznacza, że pojawią się na szczycie listy pomimo, że według daty będą później. Ze względu, ze lista wpisów może długa przydatna wydaje się być paginacja. Wpisy na blogu powinny pojawiać się w formie zajawki. 

Technicznie oznacza, że trzeba zrobić `BlogController`, który zawiera akcje `index`. W środku skorzystać z [PaginationComponent](http://book.cakephp.org/3.0/en/controllers/components/pagination.html).
- [x] utworzenie kontrollera i akcji
- [x] paginacja
- [x] tylko zajawka

Z wyrazami szacunku

**Comment by ka54mil** [comment]
Właściwie to co to znaczy w formie zajawki?
I załóżmy, że mam 2 posty, najpierw dodałem post a, potem post b. Zmieniłem zdanie i zmodyfikowałem post b, to który post powinien być wyżej, post a czy post b?

**Comment by mik-laj** [comment]
Zajawka, czyli sam początek jakieś 2-3 zdania. 
Według daty utworzenia.

**Comment by mik-laj** [comment]
Do tego możesz wykorzystać metodę [TextHelper::truncate](http://book.cakephp.org/3.0/en/views/helpers/text.html#truncating-text)

**Comment by mik-laj** [comment]
Cześć zrobiona w:  https://github.com/watchdogpolska/petycja-php.siecobywatelska.pl/commit/86deb22a49ac754adff999d8c8faf1a72a56040b 

Do zrobienia zajawka i możliwość wyróżnienia wpisu.

**Comment by mik-laj** [comment]
Do zrobienia możliwość wyróżnienia wpisu.
